name: Run pytest

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    name: run pytest
    steps:
    - name: Send Notify
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.chat_id }}
        token: ${{ secrets.bot_token }}
        format: markdown
        message: |
          Action Trigger
          ==========
          Repo: `${{ github.repository }}`
          Commit: `${{ github.sha }}`
          ==========
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
    - name: run pytests
      continue-on-error: true
      run: |
        pip install pytest
        pytest --cov=hexlightning --cov-report=xml --rootdir=./hexlightning tests
    - name: upload codecov
      run: |
        export CODACY_PROJECT_TOKEN=${{ secrets.codecay_token }}
        python-codacy-coverage -r coverage.xml

